### PR TITLE
API contract for external accounts

### PR DESCRIPTION
**Pull request by rohan09-raj**
## API Contracts
- **GET** :  `/external-accounts/:token`
    - Fetches the attributes of external accounts using a unique token given to user
    - Requires user authentication to get the data
    - Data can be queried according to the `type`
- **POST** : `/external-accounts`
    - Requires JWT authentication to authorize the account in Headers
    -  Requires Body
       ```json
       {
         "type": "<ACCOUNT_TYPE> (String)",
         "token": "<ENCRYPTED_TOKEN> (String)",
         "attributes": "<ACCOUNT_ATTRIBUTES> (Object)",
       }
       ```

### CODE REVIEW

**Review by samyakshah3008 — APPROVED** [review]
Looks good to approve ✅

**Review by shubhamsigdar1 — APPROVED** [review]
All good

**Review by heyrandhir — APPROVED** [review]
LGTM 👍🏻

**Review by shmbajaj — COMMENTED** [review]
Correct me if am not wrong,
For ``` POST /external-accounts``` body required is

```json
       {
         "type": "<ACCOUNT_TYPE> (String)",
         "attributes": "<ACCOUNT_ATTRIBUTES> (Object)",
       }
```
But in description stated like this:
(and createdOn shouldn't be part of the body if the below description is correct)
```json
       {
         "type": "<ACCOUNT_TYPE> (String)",
         "token": "<ENCRYPTED_TOKEN> (String)",
         "createdOn": "<CURRENT_TIME_TIMESTAMP> (Timestamp)",
         "attributes": "<ACCOUNT_ATTRIBUTES> (Object)",
       }
```

Check is description update required, I felt confused.

**Comment by rohan09-raj** [comment]
Thanks for pointing out, description one is correct, let me update the contract as well @shmbajaj

**Review by shmbajaj — APPROVED** [review]

**Review by samyakshah3008 — APPROVED** [review]
Great work, Rohan!

**Review by shubhamsigdar1 — APPROVED** [review]

**Review by heyrandhir — APPROVED** [review]

**Pull request merged**
